export const themeTokens = {
  light: {
    background: '#f8fafc',
    surface: '#ffffff',
    text: '#0f172a',
    mutedText: '#475569',
    primary: '#3366cc',
    primaryContrast: '#ffffff',
    primarySubtle: '#eff6ff',
    accent: '#f97316',
    accentContrast: '#0f172a',
    accentSubtle: '#fff7ed',
    accentAction: '#f97316',
    accentActionContrast: '#3b1a0a',
    success: '#15803d',
    successContrast: '#ffffff',
    successSubtle: '#f0fdf4',
    danger: '#b91c1c',
    input: '#ffffff',
    border: '#cbd5e1',
  },
  dark: {
    background: '#0f172a',
    surface: '#1e293b',
    text: '#f8fafc',
    mutedText: '#cbd5e1',
    primary: '#7aa2f7',
    primaryContrast: '#0f172a',
    primarySubtle: '#172554',
    accent: '#fb923c',
    accentContrast: '#0f172a',
    accentSubtle: '#3f2a1d',
    accentAction: '#f97316',
    accentActionContrast: '#3b1a0a',
    success: '#86efac',
    successContrast: '#052e16',
    successSubtle: '#052e16',
    danger: '#fca5a5',
    input: '#0f172a',
    border: '#475569',
  },
  spacing: {
    screen: 24,
    section: 16,
  },
  radius: {
    card: 12,
    control: 8,
  },
  minimumTouchTarget: 44,
} as const;

export type ThemeColors = (typeof themeTokens)['light'] | (typeof themeTokens)['dark'];
export type ThemeMode = 'light' | 'dark';
