<?php

return [
    'categories' => [
        'firsts' => 'First milestones',
        'books' => 'Books completed',
        'testaments' => 'Testaments completed',
        'streaks' => 'Reading streaks',
        'consistency' => 'Weekly consistency',
        'progress' => 'Bible progress',
    ],

    'definitions' => [
        'first_reading' => [
            'category' => 'firsts',
            'display_name' => 'First reading',
            'description' => 'You logged your first Bible reading.',
            'icon' => 'sparkles',
            'style' => 'success',
            'sort_order' => 10,
        ],
        'first_month' => [
            'category' => 'firsts',
            'display_name' => 'First 30 reading days',
            'description' => 'You logged 30 distinct reading days.',
            'icon' => 'calendar-check',
            'style' => 'primary',
            'sort_order' => 30,
            'threshold' => 30,
        ],
        'book_completed' => [
            'category' => 'books',
            'display_name' => 'Book completed',
            'description' => 'You completed a book of the Bible.',
            'icon' => 'book-open',
            'style' => 'success',
            'sort_order' => 100,
        ],
        'testament_completed' => [
            'category' => 'testaments',
            'display_name' => 'Testament completed',
            'description' => 'You completed every book in a testament.',
            'icon' => 'library',
            'style' => 'warning',
            'sort_order' => 200,
        ],
        'reading_streak_7' => [
            'category' => 'streaks',
            'display_name' => '7-day reading streak',
            'description' => 'You read for 7 days in a row.',
            'icon' => 'flame',
            'style' => 'accent',
            'sort_order' => 310,
            'threshold' => 7,
        ],
        'reading_streak_30' => [
            'category' => 'streaks',
            'display_name' => '30-day reading streak',
            'description' => 'You read for 30 days in a row.',
            'icon' => 'flame',
            'style' => 'accent',
            'sort_order' => 320,
            'threshold' => 30,
        ],
        'reading_streak_100' => [
            'category' => 'streaks',
            'display_name' => '100-day reading streak',
            'description' => 'You read for 100 days in a row.',
            'icon' => 'flame',
            'style' => 'accent',
            'sort_order' => 330,
            'threshold' => 100,
        ],
        'reading_streak_365' => [
            'category' => 'streaks',
            'display_name' => '365-day reading streak',
            'description' => 'You read for 365 days in a row.',
            'icon' => 'flame',
            'style' => 'accent',
            'sort_order' => 340,
            'threshold' => 365,
        ],
        'weekly_consistency_4' => [
            'category' => 'consistency',
            'display_name' => '4-week target streak',
            'description' => 'You reached your weekly reading target for 4 weeks in a row.',
            'icon' => 'target',
            'style' => 'primary',
            'sort_order' => 400,
            'threshold' => 4,
        ],
        'weekly_consistency_8' => [
            'category' => 'consistency',
            'display_name' => '8-week target streak',
            'description' => 'You reached your weekly reading target for 8 weeks in a row.',
            'icon' => 'target',
            'style' => 'primary',
            'sort_order' => 410,
            'threshold' => 8,
        ],
        'weekly_consistency_12' => [
            'category' => 'consistency',
            'display_name' => '12-week target streak',
            'description' => 'You reached your weekly reading target for 12 weeks in a row.',
            'icon' => 'target',
            'style' => 'primary',
            'sort_order' => 420,
            'threshold' => 12,
        ],
        'bible_progress_25' => [
            'category' => 'progress',
            'display_name' => '25% Bible progress',
            'description' => 'You crossed 25% of the Bible by chapters.',
            'icon' => 'chart',
            'style' => 'warning',
            'sort_order' => 500,
            'threshold' => 25,
        ],
        'bible_progress_50' => [
            'category' => 'progress',
            'display_name' => '50% Bible progress',
            'description' => 'You crossed 50% of the Bible by chapters.',
            'icon' => 'chart',
            'style' => 'warning',
            'sort_order' => 510,
            'threshold' => 50,
        ],
        'bible_progress_75' => [
            'category' => 'progress',
            'display_name' => '75% Bible progress',
            'description' => 'You crossed 75% of the Bible by chapters.',
            'icon' => 'chart',
            'style' => 'warning',
            'sort_order' => 520,
            'threshold' => 75,
        ],
        'bible_progress_100' => [
            'category' => 'progress',
            'display_name' => '100% Bible progress',
            'description' => 'You completed the Bible by chapters.',
            'icon' => 'chart',
            'style' => 'warning',
            'sort_order' => 530,
            'threshold' => 100,
        ],
    ],
];
