<?php

return [
    'books' => [
        // Old Testament (1-39)
        1 => [
            'id' => 1,
            'chapters' => 50,
            'testament' => 'old',
            'abbreviation' => 'Gen',
        ],
        2 => [
            'id' => 2,
            'chapters' => 40,
            'testament' => 'old',
            'abbreviation' => 'Ex',
        ],
        3 => [
            'id' => 3,
            'chapters' => 27,
            'testament' => 'old',
            'abbreviation' => 'Lev',
        ],
        4 => [
            'id' => 4,
            'chapters' => 36,
            'testament' => 'old',
            'abbreviation' => 'Num',
        ],
        5 => [
            'id' => 5,
            'chapters' => 34,
            'testament' => 'old',
            'abbreviation' => 'Deut',
        ],
        6 => [
            'id' => 6,
            'chapters' => 24,
            'testament' => 'old',
            'abbreviation' => 'Josh',
        ],
        7 => [
            'id' => 7,
            'chapters' => 21,
            'testament' => 'old',
            'abbreviation' => 'Jdg',
        ],
        8 => [
            'id' => 8,
            'chapters' => 4,
            'testament' => 'old',
            'abbreviation' => 'Rut',
        ],
        9 => [
            'id' => 9,
            'chapters' => 31,
            'testament' => 'old',
            'abbreviation' => '1 Sa',
        ],
        10 => [
            'id' => 10,
            'chapters' => 24,
            'testament' => 'old',
            'abbreviation' => '2 Sa',
        ],
        11 => [
            'id' => 11,
            'chapters' => 22,
            'testament' => 'old',
            'abbreviation' => '1 Kgs',
        ],
        12 => [
            'id' => 12,
            'chapters' => 25,
            'testament' => 'old',
            'abbreviation' => '2 Kgs',
        ],
        13 => [
            'id' => 13,
            'chapters' => 29,
            'testament' => 'old',
            'abbreviation' => '1 Chr',
        ],
        14 => [
            'id' => 14,
            'chapters' => 36,
            'testament' => 'old',
            'abbreviation' => '2 Chr',
        ],
        15 => [
            'id' => 15,
            'chapters' => 10,
            'testament' => 'old',
            'abbreviation' => 'Ezr',
        ],
        16 => [
            'id' => 16,
            'chapters' => 13,
            'testament' => 'old',
            'abbreviation' => 'Neh',
        ],
        17 => [
            'id' => 17,
            'chapters' => 10,
            'testament' => 'old',
            'abbreviation' => 'Est',
        ],
        18 => [
            'id' => 18,
            'chapters' => 42,
            'testament' => 'old',
            'abbreviation' => 'Job',
        ],
        19 => [
            'id' => 19,
            'chapters' => 150,
            'testament' => 'old',
            'abbreviation' => 'Ps',
        ],
        20 => [
            'id' => 20,
            'chapters' => 31,
            'testament' => 'old',
            'abbreviation' => 'Pro',
        ],
        21 => [
            'id' => 21,
            'chapters' => 12,
            'testament' => 'old',
            'abbreviation' => 'Ecc',
        ],
        22 => [
            'id' => 22,
            'chapters' => 8,
            'testament' => 'old',
            'abbreviation' => 'Sos',
        ],
        23 => [
            'id' => 23,
            'chapters' => 66,
            'testament' => 'old',
            'abbreviation' => 'Isa',
        ],
        24 => [
            'id' => 24,
            'chapters' => 52,
            'testament' => 'old',
            'abbreviation' => 'Jer',
        ],
        25 => [
            'id' => 25,
            'chapters' => 5,
            'testament' => 'old',
            'abbreviation' => 'Lam',
        ],
        26 => [
            'id' => 26,
            'chapters' => 48,
            'testament' => 'old',
            'abbreviation' => 'Eze',
        ],
        27 => [
            'id' => 27,
            'chapters' => 12,
            'testament' => 'old',
            'abbreviation' => 'Dan',
        ],
        28 => [
            'id' => 28,
            'chapters' => 14,
            'testament' => 'old',
            'abbreviation' => 'Hos',
        ],
        29 => [
            'id' => 29,
            'chapters' => 3,
            'testament' => 'old',
            'abbreviation' => 'Joe',
        ],
        30 => [
            'id' => 30,
            'chapters' => 9,
            'testament' => 'old',
            'abbreviation' => 'Amo',
        ],
        31 => [
            'id' => 31,
            'chapters' => 1,
            'testament' => 'old',
            'abbreviation' => 'Oba',
        ],
        32 => [
            'id' => 32,
            'chapters' => 4,
            'testament' => 'old',
            'abbreviation' => 'Jon',
        ],
        33 => [
            'id' => 33,
            'chapters' => 7,
            'testament' => 'old',
            'abbreviation' => 'Mic',
        ],
        34 => [
            'id' => 34,
            'chapters' => 3,
            'testament' => 'old',
            'abbreviation' => 'Nah',
        ],
        35 => [
            'id' => 35,
            'chapters' => 3,
            'testament' => 'old',
            'abbreviation' => 'Hab',
        ],
        36 => [
            'id' => 36,
            'chapters' => 3,
            'testament' => 'old',
            'abbreviation' => 'Zep',
        ],
        37 => [
            'id' => 37,
            'chapters' => 2,
            'testament' => 'old',
            'abbreviation' => 'Hag',
        ],
        38 => [
            'id' => 38,
            'chapters' => 14,
            'testament' => 'old',
            'abbreviation' => 'Zec',
        ],
        39 => [
            'id' => 39,
            'chapters' => 4,
            'testament' => 'old',
            'abbreviation' => 'Mal',
        ],

        // New Testament (40-66)
        40 => [
            'id' => 40,
            'chapters' => 28,
            'testament' => 'new',
            'abbreviation' => 'Mat',
        ],
        41 => [
            'id' => 41,
            'chapters' => 16,
            'testament' => 'new',
            'abbreviation' => 'Mk',
        ],
        42 => [
            'id' => 42,
            'chapters' => 24,
            'testament' => 'new',
            'abbreviation' => 'Luk',
        ],
        43 => [
            'id' => 43,
            'chapters' => 21,
            'testament' => 'new',
            'abbreviation' => 'John',
        ],
        44 => [
            'id' => 44,
            'chapters' => 28,
            'testament' => 'new',
            'abbreviation' => 'Acts',
        ],
        45 => [
            'id' => 45,
            'chapters' => 16,
            'testament' => 'new',
            'abbreviation' => 'Rom',
        ],
        46 => [
            'id' => 46,
            'chapters' => 16,
            'testament' => 'new',
            'abbreviation' => '1 Co',
        ],
        47 => [
            'id' => 47,
            'chapters' => 13,
            'testament' => 'new',
            'abbreviation' => '2 Co',
        ],
        48 => [
            'id' => 48,
            'chapters' => 6,
            'testament' => 'new',
            'abbreviation' => 'Gal',
        ],
        49 => [
            'id' => 49,
            'chapters' => 6,
            'testament' => 'new',
            'abbreviation' => 'Eph',
        ],
        50 => [
            'id' => 50,
            'chapters' => 4,
            'testament' => 'new',
            'abbreviation' => 'Phil',
        ],
        51 => [
            'id' => 51,
            'chapters' => 4,
            'testament' => 'new',
            'abbreviation' => 'Col',
        ],
        52 => [
            'id' => 52,
            'chapters' => 5,
            'testament' => 'new',
            'abbreviation' => '1 Th',
        ],
        53 => [
            'id' => 53,
            'chapters' => 3,
            'testament' => 'new',
            'abbreviation' => '2 Th',
        ],
        54 => [
            'id' => 54,
            'chapters' => 6,
            'testament' => 'new',
            'abbreviation' => '1 Ti',
        ],
        55 => [
            'id' => 55,
            'chapters' => 4,
            'testament' => 'new',
            'abbreviation' => '2 Ti',
        ],
        56 => [
            'id' => 56,
            'chapters' => 3,
            'testament' => 'new',
            'abbreviation' => 'Tit',
        ],
        57 => [
            'id' => 57,
            'chapters' => 1,
            'testament' => 'new',
            'abbreviation' => 'Phlm',
        ],
        58 => [
            'id' => 58,
            'chapters' => 13,
            'testament' => 'new',
            'abbreviation' => 'Heb',
        ],
        59 => [
            'id' => 59,
            'chapters' => 5,
            'testament' => 'new',
            'abbreviation' => 'Jam',
        ],
        60 => [
            'id' => 60,
            'chapters' => 5,
            'testament' => 'new',
            'abbreviation' => '1 Pe',
        ],
        61 => [
            'id' => 61,
            'chapters' => 3,
            'testament' => 'new',
            'abbreviation' => '2 Pe',
        ],
        62 => [
            'id' => 62,
            'chapters' => 5,
            'testament' => 'new',
            'abbreviation' => '1 Jn',
        ],
        63 => [
            'id' => 63,
            'chapters' => 1,
            'testament' => 'new',
            'abbreviation' => '2 Jn',
        ],
        64 => [
            'id' => 64,
            'chapters' => 1,
            'testament' => 'new',
            'abbreviation' => '3 Jn',
        ],
        65 => [
            'id' => 65,
            'chapters' => 1,
            'testament' => 'new',
            'abbreviation' => 'Jude',
        ],
        66 => [
            'id' => 66,
            'chapters' => 22,
            'testament' => 'new',
            'abbreviation' => 'Rev',
        ],
    ],

    'testaments' => [
        'old' => [
            'range' => [1, 39],
        ],
        'new' => [
            'range' => [40, 66],
        ],
    ],

    'default_locale' => 'en',
    'supported_locales' => ['en', 'fr'],
];
