<?php

return [
    'books' => [
        // Old Testament (1-39)
        1 => [
            'id' => 1,
            'chapters' => 50,
            'testament' => 'old',
            'genre' => 'Law',
        ],
        2 => [
            'id' => 2,
            'chapters' => 40,
            'testament' => 'old',
            'genre' => 'Law',
        ],
        3 => [
            'id' => 3,
            'chapters' => 27,
            'testament' => 'old',
            'genre' => 'Law',
        ],
        4 => [
            'id' => 4,
            'chapters' => 36,
            'testament' => 'old',
            'genre' => 'Law',
        ],
        5 => [
            'id' => 5,
            'chapters' => 34,
            'testament' => 'old',
            'genre' => 'Law',
        ],
        6 => [
            'id' => 6,
            'chapters' => 24,
            'testament' => 'old',
            'genre' => 'History',
        ],
        7 => [
            'id' => 7,
            'chapters' => 21,
            'testament' => 'old',
            'genre' => 'History',
        ],
        8 => [
            'id' => 8,
            'chapters' => 4,
            'testament' => 'old',
            'genre' => 'History',
        ],
        9 => [
            'id' => 9,
            'chapters' => 31,
            'testament' => 'old',
            'genre' => 'History',
        ],
        10 => [
            'id' => 10,
            'chapters' => 24,
            'testament' => 'old',
            'genre' => 'History',
        ],
        11 => [
            'id' => 11,
            'chapters' => 22,
            'testament' => 'old',
            'genre' => 'History',
        ],
        12 => [
            'id' => 12,
            'chapters' => 25,
            'testament' => 'old',
            'genre' => 'History',
        ],
        13 => [
            'id' => 13,
            'chapters' => 29,
            'testament' => 'old',
            'genre' => 'History',
        ],
        14 => [
            'id' => 14,
            'chapters' => 36,
            'testament' => 'old',
            'genre' => 'History',
        ],
        15 => [
            'id' => 15,
            'chapters' => 10,
            'testament' => 'old',
            'genre' => 'History',
        ],
        16 => [
            'id' => 16,
            'chapters' => 13,
            'testament' => 'old',
            'genre' => 'History',
        ],
        17 => [
            'id' => 17,
            'chapters' => 10,
            'testament' => 'old',
            'genre' => 'History',
        ],
        18 => [
            'id' => 18,
            'chapters' => 42,
            'testament' => 'old',
            'genre' => 'Poetry',
        ],
        19 => [
            'id' => 19,
            'chapters' => 150,
            'testament' => 'old',
            'genre' => 'Poetry',
        ],
        20 => [
            'id' => 20,
            'chapters' => 31,
            'testament' => 'old',
            'genre' => 'Poetry',
        ],
        21 => [
            'id' => 21,
            'chapters' => 12,
            'testament' => 'old',
            'genre' => 'Poetry',
        ],
        22 => [
            'id' => 22,
            'chapters' => 8,
            'testament' => 'old',
            'genre' => 'Poetry',
        ],
        23 => [
            'id' => 23,
            'chapters' => 66,
            'testament' => 'old',
            'genre' => 'Major Prophets',
        ],
        24 => [
            'id' => 24,
            'chapters' => 52,
            'testament' => 'old',
            'genre' => 'Major Prophets',
        ],
        25 => [
            'id' => 25,
            'chapters' => 5,
            'testament' => 'old',
            'genre' => 'Major Prophets',
        ],
        26 => [
            'id' => 26,
            'chapters' => 48,
            'testament' => 'old',
            'genre' => 'Major Prophets',
        ],
        27 => [
            'id' => 27,
            'chapters' => 12,
            'testament' => 'old',
            'genre' => 'Major Prophets',
        ],
        28 => [
            'id' => 28,
            'chapters' => 14,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        29 => [
            'id' => 29,
            'chapters' => 3,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        30 => [
            'id' => 30,
            'chapters' => 9,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        31 => [
            'id' => 31,
            'chapters' => 1,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        32 => [
            'id' => 32,
            'chapters' => 4,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        33 => [
            'id' => 33,
            'chapters' => 7,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        34 => [
            'id' => 34,
            'chapters' => 3,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        35 => [
            'id' => 35,
            'chapters' => 3,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        36 => [
            'id' => 36,
            'chapters' => 3,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        37 => [
            'id' => 37,
            'chapters' => 2,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        38 => [
            'id' => 38,
            'chapters' => 14,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],
        39 => [
            'id' => 39,
            'chapters' => 4,
            'testament' => 'old',
            'genre' => 'Minor Prophets',
        ],

        // New Testament (40-66)
        40 => [
            'id' => 40,
            'chapters' => 28,
            'testament' => 'new',
            'genre' => 'Gospels',
        ],
        41 => [
            'id' => 41,
            'chapters' => 16,
            'testament' => 'new',
            'genre' => 'Gospels',
        ],
        42 => [
            'id' => 42,
            'chapters' => 24,
            'testament' => 'new',
            'genre' => 'Gospels',
        ],
        43 => [
            'id' => 43,
            'chapters' => 21,
            'testament' => 'new',
            'genre' => 'Gospels',
        ],
        44 => [
            'id' => 44,
            'chapters' => 28,
            'testament' => 'new',
            'genre' => 'History',
        ],
        45 => [
            'id' => 45,
            'chapters' => 16,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        46 => [
            'id' => 46,
            'chapters' => 16,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        47 => [
            'id' => 47,
            'chapters' => 13,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        48 => [
            'id' => 48,
            'chapters' => 6,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        49 => [
            'id' => 49,
            'chapters' => 6,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        50 => [
            'id' => 50,
            'chapters' => 4,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        51 => [
            'id' => 51,
            'chapters' => 4,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        52 => [
            'id' => 52,
            'chapters' => 5,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        53 => [
            'id' => 53,
            'chapters' => 3,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        54 => [
            'id' => 54,
            'chapters' => 6,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        55 => [
            'id' => 55,
            'chapters' => 4,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        56 => [
            'id' => 56,
            'chapters' => 3,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        57 => [
            'id' => 57,
            'chapters' => 1,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        58 => [
            'id' => 58,
            'chapters' => 13,
            'testament' => 'new',
            'genre' => "Paul's Epistles",
        ],
        59 => [
            'id' => 59,
            'chapters' => 5,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        60 => [
            'id' => 60,
            'chapters' => 5,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        61 => [
            'id' => 61,
            'chapters' => 3,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        62 => [
            'id' => 62,
            'chapters' => 5,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        63 => [
            'id' => 63,
            'chapters' => 1,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        64 => [
            'id' => 64,
            'chapters' => 1,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        65 => [
            'id' => 65,
            'chapters' => 1,
            'testament' => 'new',
            'genre' => 'General Epistles',
        ],
        66 => [
            'id' => 66,
            'chapters' => 22,
            'testament' => 'new',
            'genre' => 'Prophecy',
        ],
    ],

    'testaments' => [
        'old' => [
            'range' => [1, 39],
        ],
        'new' => [
            'range' => [40, 66],
        ],
    ],

    'default_locale' => 'en',
    'supported_locales' => ['en', 'fr'],
];
