plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.orlandovillanueva.delight'
version = '0.1.0'

android {
  namespace "com.orlandovillanueva.delight.installersource"

  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
}

dependencyLocking {
  lockAllConfigurations()
}
